### ISSUE TITLE
Branching structure

### ISSUE THREAD

**Issue by ForNeVeR** [wieslawsoltes/wmf#2]
Currently, we have several branches:
- `master` (corresponds to [the original repo](https://github.com/papnkukn/wmf))
- `netstandard` (the main development; all the new code goes into this branch)
- `release/0.5.0` (somewhat similar to a release tag — but not a tag)

I propose:
- convert `release/0.5.0` into a tag `v0.5.0`
- merge `netstandard` into `master`
- proceed the development in `master`

@wieslawsoltes, what do you think?

**Comment by wieslawsoltes** [comment]
'release/0.5.0' is a release branch, tag is different thing

we can make main branch and have master for historic reasons

**Comment by ForNeVeR** [comment]
Could you please explain the branching structure you prefer? Having a release branch (and not a tag) is not a thing I see often in the repos I work on.

I am totally fine with it if you explain how it works :)

> we can make `main` branch for development and have `master` for historic reasons

No objections from me. Though I'd prefer to _not_ have the "historic" `master` branch then: it may be somewhat confusing (i.e. imagine someone sends us a PR and struggles to choose the target branch). People who want to follow the development history of the original repository may just go there, it is open on GitHub as well.

**Comment by wieslawsoltes** [comment]
I do create release branches e.g. `release/0.6.0` that are used for CI builds and CD releases that generate GitHub releases and appropriate tags.

**Comment by ForNeVeR** [comment]
Ok, so it is somewhat similar to a release tag, but a branch. I think I get it. Let it be, then.

So, my new proposal is to
- rename `netstandard` to `main`, and make `main` the, well, main branch here
- (optionally) drop `master`

**Comment by wieslawsoltes** [comment]
> Ok, so it is somewhat similar to a release tag, but a branch. I think I get it. Let it be, then.
> 
> So, my new proposal is to
> 
> * rename `netstandard` to `main`, and make `main` the, well, main branch here
> * (optionally) drop `master`

Done.

**Comment by ForNeVeR** [comment]
Thanks!

**Comment by ForNeVeR** [comment]
(I guess you've decided to leave `master` for now? Alright.)

**Comment by wieslawsoltes** [comment]
Pushed for now manually 0.6 release https://www.nuget.org/packages/Oxage.Wmf/0.6.0

**Comment by wieslawsoltes** [comment]
> (I guess you've decided to leave `master` for now? Alright.)

yes, I like to have it for history

**Comment by wieslawsoltes** [comment]
@ForNeVeR I have setup full CI/CD pipeline. Will do next test release. I also updated to .NET 7.

**Comment by ForNeVeR** [comment]
That's great. I was thinking about setting up a CI, but decided we won't likely have too many releases in the near future, so didn't want to raise this question. But what you did is awesome.
